# Generated by Django 4.1.2 on 2022-11-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categories_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='publish_date',
            field=models.DateField(null=True),
        ),
    ]
