# Generated by Django 4.1.2 on 2022-11-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_posts_publish_date'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='posts',
            order_with_respect_to='publish_date',
        ),
    ]
