# Generated by Django 4.1.2 on 2022-11-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_posts_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-publish_date']},
        ),
    ]
