# Generated by Django 4.1.2 on 2022-11-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_posts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='dislikes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
