# Generated by Django 4.1.2 on 2022-11-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='likes',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
